# Konfigurasi Haxorport Client untuk Production
server_address: control.haxorport.online
control_port: 443
tls_enabled: true  # Gunakan TLS (WSS) untuk koneksi WebSocket
auth_token: ""  # Token autentikasi jika diperlukan
log_level: info  # Gunakan info untuk output yang lebih bersih
log_file: "logs/haxor-client.log"    # Kosong untuk output ke stdout
